name: Daily Digest

on:
  schedule:
    - cron: "0 6 * * *"   # täglich um 06:00 UTC
  workflow_dispatch:       # manuell starten möglich

jobs:
  digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run digest
        run: python digest.py
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: digest
          path: out/
